export const EQUIPMENT_ARTICLES: Record<string, string> = {
  'feed-crude': 'feed-system',
  'parks-55-5': 'feed-system',
  'L-1': 'feed-system',
  'N-1': 'feed-pumps',
  'N-2': 'furnace-operation',
  'N-3': 'furnace-operation',
  'ELOU-block': 'elou-principle',
  'E-1': 'electro-dehydrators',
  'E-2': 'electro-dehydrators',
  'E-3': 'electro-dehydrators',
  'E-4': 'electro-dehydrators',
  'E-5': 'electro-dehydrators',
  'E-6': 'electro-dehydrators',
  'Q_ELOU': 'elou-quality',
  'K-1': 'k1-control',
  'K-2': 'k2-control',
  'E-1-vessel': 'e1-water',
  'E-2-vessel': 'e1-water',
  'P-1': 'furnace-operation',
  'P-2': 'furnace-operation',
  'P-3': 'furnace-operation',
  'P-4': 'furnace-operation',
  'AVZ-3': 'cooling-system',
  'UTIL-block': 'instrument-air',
}
