import type { EquipmentNode } from './types'

/**
 * Дополнения к схеме КТС.
 * Раскладка: основной поток без плотных подписей;
 * детализация Т-x / фракции / газ — в нижних полосах зон.
 */
export const equipmentExtras: EquipmentNode[] = [
  // ——— Утилиты: отдельная колонка слева, ниже парков ———
  {
    id: 'UTIL-steam-hp',
    type: 'label',
    label: 'Перегретый пар',
    x: 40,
    y: 900,
    w: 130,
    h: 30,
    meta: { zone: '1. Сырьё', description: 'Перегретый пар 25 ати (схема КТС)' },
  },
  {
    id: 'UTIL-steam-sharp',
    type: 'label',
    label: 'Остр пар',
    x: 40,
    y: 940,
    w: 90,
    h: 30,
    meta: { zone: '1. Сырьё', description: 'Острый пар 10 ати' },
  },
  {
    id: 'UTIL-river',
    type: 'label',
    label: 'Речная вода',
    x: 40,
    y: 980,
    w: 110,
    h: 30,
    meta: { zone: '1. Сырьё', description: 'Речная вода на подогрев / охлаждение' },
  },
  {
    id: 'UTIL-nitrogen',
    type: 'label',
    label: 'Азот',
    x: 40,
    y: 1020,
    w: 70,
    h: 30,
    meta: { zone: '1. Сырьё', description: 'Заводская сеть азота' },
  },
  {
    id: 'UTIL-tech-air',
    type: 'label',
    label: 'Тех. воздух',
    x: 40,
    y: 1060,
    w: 110,
    h: 30,
    meta: { zone: '1. Сырьё', description: 'Технический воздух' },
  },
  {
    id: 'UTIL-vsg',
    type: 'label',
    label: 'ВСГ из завод. сети',
    x: 40,
    y: 1100,
    w: 140,
    h: 30,
    meta: { zone: '1. Сырьё', description: 'ВСГ для сушки катализатора' },
  },
  {
    id: 'lin-339',
    type: 'label',
    label: 'лин-339',
    x: 40,
    y: 1140,
    w: 80,
    h: 30,
    meta: { zone: '1. Сырьё', description: 'Линия 339 (схема КТС)' },
  },
  {
    id: 'P-5',
    type: 'pump',
    label: 'П-5',
    x: 190,
    y: 960,
    w: 56,
    h: 56,
    meta: {
      zone: '1. Сырьё',
      description: 'Насос контура пара / воды (схема КТС)',
    },
  },

  // ——— Реагенты: панель под ЭЛОУ (всё внутри рамки, заголовок сверху) ———
  {
    id: 'reagent-panel',
    type: 'group',
    label: ' ',
    x: 640,
    y: 700,
    w: 300,
    h: 230,
    meta: { zone: '3. ЭЛОУ', description: 'Блок дозирования реагентов' },
  },
  {
    id: 'reagent-panel-title',
    type: 'label',
    label: 'Реагенты ЭЛОУ',
    x: 655,
    y: 710,
    w: 140,
    h: 24,
    meta: { zone: '3. ЭЛОУ', description: 'Блок дозирования реагентов' },
  },
  {
    id: 'reagent-deemulsifier',
    type: 'label',
    label: 'Деэмульгатор',
    x: 655,
    y: 745,
    w: 130,
    h: 28,
    meta: { zone: '3. ЭЛОУ', description: 'Деэмульгатор на вход ЭЛОУ' },
  },
  {
    id: 'reagent-naoh',
    type: 'label',
    label: 'NaOH',
    x: 800,
    y: 745,
    w: 120,
    h: 28,
    meta: { zone: '3. ЭЛОУ', description: 'Щёлочь на ЭЛОУ' },
  },
  {
    id: 'reagent-inhibitor',
    type: 'label',
    label: 'Р-р ингибитора',
    x: 655,
    y: 790,
    w: 130,
    h: 28,
    meta: { zone: '3. ЭЛОУ', description: 'Раствор ингибитора коррозии' },
  },
  {
    id: 'reagent-neutralizer',
    type: 'label',
    label: 'Р-р нейтрализатора',
    x: 800,
    y: 790,
    w: 120,
    h: 28,
    meta: { zone: '3. ЭЛОУ', description: 'Раствор нейтрализатора' },
  },
  {
    id: 'reagent-weak-alkali',
    type: 'label',
    label: 'Р-р слабой щелочи',
    x: 655,
    y: 835,
    w: 265,
    h: 28,
    meta: { zone: '3. ЭЛОУ', description: 'Слабая щёлочь (схема КТС)' },
  },
  {
    id: 'ELOU-2-label',
    type: 'label',
    label: 'ЭЛОУ-2',
    x: 700,
    y: 500,
    w: 80,
    h: 28,
    meta: { zone: '3. ЭЛОУ', description: 'Вторая ступень ЭЛОУ (схема КТС)' },
  },
  {
    id: 'desalted-oil',
    type: 'label',
    label: 'Обессол.\nнефть',
    x: 885,
    y: 392,
    w: 64,
    h: 36,
    meta: { zone: '3. ЭЛОУ', description: 'Обессоленная нефть после ЭЛОУ' },
  },

  // ——— Т-1…Т-11: полоса под блоком подогрева (не рядом с потоками) ———
  {
    id: 'HX-detail-band',
    type: 'group',
    label: 'Т-1…Т-11 (детализация)',
    x: 320,
    y: 1000,
    w: 520,
    h: 150,
    meta: { zone: '2. Подогрев', description: 'Единичные теплообменники потоков' },
  },
  {
    id: 'T-1',
    type: 'heatExchanger',
    label: 'Т-1',
    x: 340,
    y: 1045,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 1 потока (Т-1/1-3)' },
  },
  {
    id: 'T-2',
    type: 'heatExchanger',
    label: 'Т-2',
    x: 400,
    y: 1045,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 1 потока' },
  },
  {
    id: 'T-3',
    type: 'heatExchanger',
    label: 'Т-3',
    x: 460,
    y: 1045,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 1 потока (Т-3/1-2)' },
  },
  {
    id: 'T-4',
    type: 'heatExchanger',
    label: 'Т-4',
    x: 540,
    y: 1045,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 2 потока (Т-4/1-2)' },
  },
  {
    id: 'T-5',
    type: 'heatExchanger',
    label: 'Т-5',
    x: 600,
    y: 1045,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 2 потока' },
  },
  {
    id: 'T-6',
    type: 'heatExchanger',
    label: 'Т-6',
    x: 660,
    y: 1045,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 2 потока (Т-6/1-2)' },
  },
  {
    id: 'T-7',
    type: 'heatExchanger',
    label: 'Т-7',
    x: 720,
    y: 1045,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 2/3 потока' },
  },
  {
    id: 'T-8',
    type: 'heatExchanger',
    label: 'Т-8',
    x: 400,
    y: 1095,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 3 потока' },
  },
  {
    id: 'T-9',
    type: 'heatExchanger',
    label: 'Т-9',
    x: 460,
    y: 1095,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 3 потока' },
  },
  {
    id: 'T-10',
    type: 'heatExchanger',
    label: 'Т-10',
    x: 520,
    y: 1095,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 3 потока' },
  },
  {
    id: 'T-11',
    type: 'heatExchanger',
    label: 'Т-11',
    x: 580,
    y: 1095,
    w: 48,
    h: 36,
    meta: { zone: '2. Подогрев', description: 'Теплообменник 3 потока' },
  },

  // ——— ГДМ ———
  {
    id: 'K-12-1',
    type: 'column',
    label: 'К-12/1',
    x: 1460,
    y: 70,
    w: 64,
    h: 80,
    meta: {
      zone: '4–5. ГДМ',
      description: 'Колонна К-12/1 (схема КТС)',
      trays: 2,
    },
  },
  {
    id: 'T-23',
    type: 'heatExchanger',
    label: 'Т-23',
    x: 1780,
    y: 620,
    w: 70,
    h: 48,
    meta: { zone: '4–5. ГДМ', description: 'Теплообменник Т-23 (вода из завод. сети)' },
  },

  // ——— Факел: справа от ГДМ, свободная зона ———
  {
    id: 'E-44',
    type: 'vessel',
    label: 'Е-44',
    x: 1820,
    y: 80,
    w: 70,
    h: 60,
    meta: {
      zone: '4. Атмосферный',
      description: 'Ёмкость факельной системы (схема КТС)',
    },
  },
  {
    id: 'flare-stack',
    type: 'label',
    label: 'факел',
    x: 1910,
    y: 90,
    w: 64,
    h: 28,
    meta: { zone: '4. Атмосферный', description: 'Факельная система' },
  },
  {
    id: 'nekonditsiya',
    type: 'label',
    label: 'Некондиция → Е-44К',
    x: 1820,
    y: 150,
    w: 150,
    h: 28,
    meta: { zone: '4. Атмосферный', description: 'Некондиция на факельную линию' },
  },

  // ——— Фракции / газ: нижняя полоса аннотаций (не рядом с колоннами) ———
  {
    id: 'frac-85-180',
    type: 'label',
    label: 'Фр.85–180 С',
    x: 1160,
    y: 1000,
    w: 110,
    h: 28,
    meta: { zone: '4. Атмосферный', description: 'Фракция 85–180 °C' },
  },
  {
    id: 'frac-unstable-nk180',
    type: 'label',
    label: 'Нестаб.фр.НК-180С',
    x: 1290,
    y: 1000,
    w: 140,
    h: 28,
    meta: { zone: '4. Атмосферный', description: 'Нестабильная фракция НК-180 °C' },
  },
  {
    id: 'gas-from-e15',
    type: 'label',
    label: 'Газ из Е-15',
    x: 1160,
    y: 1045,
    w: 110,
    h: 28,
    meta: { zone: '3. ЭЛОУ', description: 'Газовый поток из Е-15' },
  },
  {
    id: 'gas-to-furnaces',
    type: 'label',
    label: 'Газ к печам',
    x: 1290,
    y: 1045,
    w: 110,
    h: 28,
    meta: { zone: '4. Атмосферный', description: 'Газ на печи П-1…П-3' },
  },
  {
    id: 'transfer-steam',
    type: 'label',
    label: 'Пер пар',
    x: 1420,
    y: 1045,
    w: 80,
    h: 28,
    meta: { zone: '4. Атмосферный', description: 'Перегретый пар на печи' },
  },

  {
    id: 'frac-140-240',
    type: 'label',
    label: 'Фр.140–240 С',
    x: 1980,
    y: 1000,
    w: 120,
    h: 28,
    meta: { zone: '5. К-2 / стриппинги', description: 'Фракция 140–240 °C' },
  },
  {
    id: 'frac-240-300',
    type: 'label',
    label: 'Фр.240–300 С',
    x: 2120,
    y: 1000,
    w: 120,
    h: 28,
    meta: { zone: '5. К-2 / стриппинги', description: 'Фракция 240–300 °C' },
  },
  {
    id: 'frac-300-350',
    type: 'label',
    label: 'Фр.300–350 С',
    x: 2260,
    y: 1000,
    w: 120,
    h: 28,
    meta: { zone: '5. К-2 / стриппинги', description: 'Фракция 300–350 °C' },
  },
  {
    id: 'mazut-stream-1',
    type: 'label',
    label: '1 поток мазута',
    x: 1980,
    y: 1045,
    w: 120,
    h: 28,
    meta: { zone: '5. К-2 / стриппинги', description: '1 поток мазута с К-2' },
  },
  {
    id: 'mazut-stream-2',
    type: 'label',
    label: '2 поток мазута',
    x: 2120,
    y: 1045,
    w: 120,
    h: 28,
    meta: { zone: '5. К-2 / стриппинги', description: '2 поток мазута с К-2' },
  },
  {
    id: 'to-opu',
    type: 'label',
    label: 'на ОПУ',
    x: 2260,
    y: 1045,
    w: 80,
    h: 28,
    meta: { zone: '5. К-2 / стриппинги', description: 'Вывод на ОПУ' },
  },

  {
    id: 'frac-40-180',
    type: 'label',
    label: 'Фр.40–180 С',
    x: 2500,
    y: 1000,
    w: 110,
    h: 28,
    meta: { zone: '6. Стабилизация', description: 'Фракция 40–180 °C' },
  },
  {
    id: 'frac-105-180',
    type: 'label',
    label: 'Фр.105–180 С',
    x: 2630,
    y: 1000,
    w: 120,
    h: 28,
    meta: { zone: '6. Стабилизация', description: 'Фракция 105–180 °C' },
  },
  {
    id: 'frac-stable-nk180',
    type: 'label',
    label: 'Стаб. фр.НК-180С',
    x: 2770,
    y: 1000,
    w: 130,
    h: 28,
    meta: { zone: '6. Стабилизация', description: 'Стабильная фракция НК-180 °C' },
  },
  {
    id: 'butane',
    type: 'label',
    label: 'Бутан',
    x: 2500,
    y: 1045,
    w: 80,
    h: 28,
    meta: { zone: '6. Стабилизация', description: 'Сжиженный бутан' },
  },
  {
    id: 'pbf-gfu',
    type: 'label',
    label: 'ПБФ на ГФУ',
    x: 2600,
    y: 1045,
    w: 110,
    h: 28,
    meta: { zone: '6. Стабилизация', description: 'ПБФ на газофракционную установку' },
  },
  {
    id: 'gas-ukg',
    type: 'label',
    label: 'Газ на УКГ',
    x: 2730,
    y: 1045,
    w: 110,
    h: 28,
    meta: { zone: '6. Стабилизация', description: 'Газ на установку компримирования' },
  },
  {
    id: 'gas-line',
    type: 'label',
    label: 'линия газа',
    x: 2860,
    y: 1045,
    w: 100,
    h: 28,
    meta: { zone: '6. Стабилизация', description: 'Линия газа (схема КТС)' },
  },
  {
    id: 'offspec-n10',
    type: 'label',
    label: 'В рез N10 (некондиция)',
    x: 2500,
    y: 1090,
    w: 170,
    h: 28,
    meta: { zone: '6. Стабилизация', description: 'Некондиция в резервуар Н-10' },
  },

  {
    id: 'frac-nk-62',
    type: 'label',
    label: 'Фр.НК-62 С',
    x: 3020,
    y: 1000,
    w: 110,
    h: 28,
    meta: { zone: '7. Вторичная', description: 'Фракция НК-62 °C' },
  },
  {
    id: 'frac-62-105',
    type: 'label',
    label: 'Фр.62–105 С',
    x: 3150,
    y: 1000,
    w: 110,
    h: 28,
    meta: { zone: '7. Вторичная', description: 'Фракция 62–105 °C' },
  },
]
