import type { EquipmentNode } from './types'

/**
 * Каталог оборудования мнемосхемы ЭЛОУ-АВТ по схеме КТС + регламенту.
 * Раскладка SCADA по зонам (слева направо), не пиксели PDF.
 */
export const equipment: EquipmentNode[] = [
  // ——— Зона 1: Сырьё / парки ———
  {
    id: 'parks-55-5',
    type: 'group',
    label: 'Парки тит. 55/5',
    x: 40,
    y: 520,
    w: 110,
    h: 160,
    meta: {
      zone: '1. Сырьё',
      description: 'Резервуары Р-10…Р-15: сырая нефть, бензины, некондиция',
    },
  },
  {
    id: 'feed-crude',
    type: 'label',
    label: 'Сырая нефть',
    x: 60,
    y: 440,
    w: 100,
    h: 36,
    meta: { zone: '1. Сырьё', description: 'Подача с КС / парков на приём Н-1' },
  },
  {
    id: 'N-1',
    type: 'pump',
    label: 'Н-1',
    x: 230,
    y: 560,
    w: 72,
    h: 72,
    meta: {
      zone: '1. Сырьё',
      description: 'Сырьевой насос',
      reserves: ['Н-1А', 'Н-1Б', 'Н-1В'],
      designPressure: '19,5 кгс/см²',
    },
  },
  {
    id: 'L-1',
    type: 'valve',
    label: 'Л-1',
    x: 160,
    y: 572,
    w: 48,
    h: 48,
    meta: {
      zone: '1. Сырьё',
      description: 'Электрозадвижка на входе сырья',
    },
  },
  {
    id: 'PR_351',
    type: 'signal',
    label: 'PRA351',
    x: 200,
    y: 500,
    w: 72,
    h: 36,
    meta: {
      zone: '1. Сырьё',
      description: 'Давление на выкиде Н-1',
    },
  },

  // ——— Зона 2: Подогрев сырой нефти ———
  {
    id: 'HX-stream-1',
    type: 'heatExchanger',
    label: 'Т-1…Т-3\n(1 поток)',
    x: 340,
    y: 300,
    w: 110,
    h: 70,
    meta: {
      zone: '2. Подогрев',
      description: '1 поток: Т-1/1-3, Т-2, Т-3/1-2 — нагрев до ЭЛОУ',
    },
  },
  {
    id: 'HX-stream-2',
    type: 'heatExchanger',
    label: 'Т-4…Т-7\n(2 поток)',
    x: 340,
    y: 440,
    w: 110,
    h: 70,
    meta: {
      zone: '2. Подогрев',
      description: '2 поток: Т-4/1-2, Т-5, Т-6/1-2, Т-7/1',
    },
  },
  {
    id: 'HX-stream-3',
    type: 'heatExchanger',
    label: 'Т-7…Т-11\n(3 поток)',
    x: 340,
    y: 580,
    w: 110,
    h: 70,
    meta: {
      zone: '2. Подогрев',
      description: '3 поток: Т-7/2, Т-8, Т-9…Т-11; t ≤ 140 °C',
    },
  },
  {
    id: 'HX-block-label',
    type: 'group',
    label: 'Бл. подогрева\nсырой нефти',
    x: 470,
    y: 400,
    w: 120,
    h: 90,
    meta: {
      zone: '2. Подогрев',
      description: 'Три параллельных потока Т-1…Т-11 перед ЭЛОУ',
    },
  },
  {
    id: 'X-18',
    type: 'heatExchanger',
    label: 'Х-18/3',
    x: 280,
    y: 200,
    w: 80,
    h: 50,
    meta: { zone: '2. Подогрев', description: 'Нагрев воды, подаваемой на ЭЛОУ' },
  },
  {
    id: 'X-38',
    type: 'heatExchanger',
    label: 'Х-38',
    x: 280,
    y: 720,
    w: 70,
    h: 48,
    meta: { zone: '2. Подогрев', description: 'Теплообменник (схема КТС)' },
  },
  {
    id: 'T-27-2',
    type: 'heatExchanger',
    label: 'Т-27/2',
    x: 520,
    y: 200,
    w: 70,
    h: 48,
    meta: { zone: '2. Подогрев', description: 'Теплообменник Т-27/2' },
  },
  {
    id: 'T-27-3',
    type: 'heatExchanger',
    label: 'Т-27/3',
    x: 600,
    y: 200,
    w: 70,
    h: 48,
    meta: { zone: '2. Подогрев', description: 'Теплообменник Т-27/3' },
  },
  {
    id: 'T-27-4',
    type: 'heatExchanger',
    label: 'Т-27/4',
    x: 680,
    y: 200,
    w: 70,
    h: 48,
    meta: { zone: '2. Подогрев', description: 'Теплообменник Т-27/4' },
  },
  {
    id: 'T-27-7',
    type: 'heatExchanger',
    label: 'Т-27/7',
    x: 760,
    y: 140,
    w: 70,
    h: 48,
    meta: { zone: '2. Подогрев', description: 'Теплообменник Т-27/7 (2 поток)' },
  },

  // ——— Зона 3: ЭЛОУ ———
  {
    id: 'ELOU-block',
    type: 'group',
    label: 'ЭЛОУ / ЭЛОУ-2',
    x: 640,
    y: 280,
    w: 290,
    h: 200,
    meta: {
      zone: '3. ЭЛОУ',
      description: 'Блок обессоливания: Э-1…Э-6, две ступени; вода + деэмульгатор',
    },
  },
  {
    id: 'E-1',
    type: 'desalter',
    label: 'Э-1',
    x: 660,
    y: 300,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 1 ступени' },
  },
  {
    id: 'E-3',
    type: 'desalter',
    label: 'Э-3',
    x: 750,
    y: 300,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 1 ступени' },
  },
  {
    id: 'E-5',
    type: 'desalter',
    label: 'Э-5',
    x: 840,
    y: 300,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 1 ступени' },
  },
  {
    id: 'E-2',
    type: 'desalter',
    label: 'Э-2',
    x: 660,
    y: 380,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 2 ступени' },
  },
  {
    id: 'E-4',
    type: 'desalter',
    label: 'Э-4',
    x: 750,
    y: 380,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 2 ступени' },
  },
  {
    id: 'E-6',
    type: 'desalter',
    label: 'Э-6',
    x: 840,
    y: 380,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 2 ступени' },
  },
  {
    id: 'E-15',
    type: 'vessel',
    label: 'Е-15',
    x: 960,
    y: 320,
    w: 80,
    h: 100,
    meta: {
      zone: '3. ЭЛОУ',
      description: 'Буферная ёмкость обессоленной нефти после ЭЛОУ',
      designPressure: '5,3 кгс/см²',
      designTemp: '110 °C',
    },
  },
  {
    id: 'E-16',
    type: 'vessel',
    label: 'Е-16',
    x: 960,
    y: 460,
    w: 80,
    h: 70,
    meta: {
      zone: '3. ЭЛОУ',
      description: 'Отстойник соляного раствора',
    },
  },
  {
    id: 'TR_41_2',
    type: 'signal',
    label: 'TR41-2',
    x: 560,
    y: 320,
    w: 70,
    h: 36,
    meta: { zone: '3. ЭЛОУ', description: 'Температура на входе ЭЛОУ' },
  },
  {
    id: 'Q_ELOU',
    type: 'signal',
    label: 'Q-ELOU',
    x: 880,
    y: 495,
    w: 70,
    h: 36,
    meta: { zone: '3. ЭЛОУ', description: 'Соли после ЭЛОУ, мг/л' },
  },
  {
    id: 'PRA_312',
    type: 'signal',
    label: 'PRA312',
    x: 990,
    y: 200,
    w: 70,
    h: 36,
    meta: { zone: '3. ЭЛОУ', description: 'Давление обессоленной нефти' },
  },
  {
    id: 'TR1K_21',
    type: 'signal',
    label: 'TR1K-21',
    x: 1090,
    y: 255,
    w: 72,
    h: 36,
    meta: {
      zone: '4. Атмосферный',
      description: 'Температура питания колонны К-1',
    },
  },
  {
    id: 'PRSA_204',
    type: 'signal',
    label: 'PRSA204',
    x: 1175,
    y: 175,
    w: 72,
    h: 36,
    meta: {
      zone: '4. Атмосферный',
      description: 'Давление верха К-1 (норма 1–4,5 кгс/см²)',
    },
  },
  {
    id: 'N-20',
    type: 'pump',
    label: 'Н-20',
    x: 960,
    y: 250,
    w: 56,
    h: 56,
    meta: {
      zone: '3. ЭЛОУ',
      description: 'Насос контура ЭЛОУ / щелочи',
      reserves: ['Н-20А', 'Н-20Б'],
    },
  },

  // ——— Зона 4: Атмосферный блок К-1 / печи ———
  {
    id: 'HX-desalted',
    type: 'heatExchanger',
    label: 'Бл. подогрева\nобесс. нефти',
    x: 1080,
    y: 300,
    w: 120,
    h: 80,
    meta: {
      zone: '4. Атмосферный',
      description: 'Подогрев обессоленной нефти перед К-1 / печами',
    },
  },
  {
    id: 'K-1',
    type: 'column',
    label: 'К-1',
    x: 1260,
    y: 220,
    w: 90,
    h: 320,
    meta: {
      zone: '4. Атмосферный',
      description: 'Первая ректификационная колонна',
      trays: 28,
      designPressure: '6 кгс/см²',
      designTemp: '300 °C',
    },
  },
  {
    id: 'L-2',
    type: 'valve',
    label: 'Л-2',
    x: 1535,
    y: 110,
    w: 48,
    h: 48,
    meta: {
      zone: '4. Атмосферный',
      description: 'Вывод бензина НК-180°С с верха К-1',
    },
  },
  {
    id: 'LRCA_602',
    type: 'signal',
    label: 'LRCA602',
    x: 1175,
    y: 500,
    w: 70,
    h: 36,
    meta: { zone: '4. Атмосферный', description: 'Уровень в К-1' },
  },
  {
    id: 'TR_55_1',
    type: 'signal',
    label: 'TR55-1',
    x: 1280,
    y: 840,
    w: 70,
    h: 36,
    meta: {
      zone: '4. Атмосферный',
      description: 'Температура выхода печей П-1…П-3 (норма ≤365 °C)',
    },
  },
  {
    id: 'E-1-vessel',
    type: 'vessel',
    label: 'Е-1',
    x: 1380,
    y: 200,
    w: 70,
    h: 90,
    meta: {
      zone: '4. Атмосферный',
      description: 'Ёмкость-водоотделитель колонны К-1',
    },
  },
  {
    id: 'E-44k',
    type: 'vessel',
    label: 'Е-44к',
    x: 1380,
    y: 100,
    w: 70,
    h: 70,
    meta: {
      zone: '4. Атмосферный',
      description: 'Каплеотбойник на факельной линии',
    },
  },
  {
    id: 'N-6',
    type: 'pump',
    label: 'Н-6',
    x: 1380,
    y: 320,
    w: 64,
    h: 64,
    meta: {
      zone: '4. Атмосферный',
      description: 'Орошение К-1 / сырьё в К-4',
      reserves: ['Н-6А'],
    },
  },
  {
    id: 'N-6K',
    type: 'pump',
    label: 'Н-6К',
    x: 1460,
    y: 400,
    w: 56,
    h: 56,
    meta: {
      zone: '4. Атмосферный',
      description: 'Насос Н-6К (схема КТС)',
      reserves: ['Н-6К/1'],
    },
  },
  {
    id: 'N-41B',
    type: 'pump',
    label: 'Н-41Б',
    x: 1460,
    y: 160,
    w: 56,
    h: 56,
    meta: {
      zone: '4. Атмосферный',
      description: 'Насос Н-41Б (схема КТС)',
    },
  },
  {
    id: 'N-2',
    type: 'pump',
    label: 'Н-2',
    x: 1180,
    y: 600,
    w: 64,
    h: 64,
    meta: {
      zone: '4. Атмосферный',
      description: 'Подача нефти в П-1, П-2',
      reserves: ['Н-2А', 'Н-2Б'],
    },
  },
  {
    id: 'N-3',
    type: 'pump',
    label: 'Н-3',
    x: 1280,
    y: 600,
    w: 64,
    h: 64,
    meta: {
      zone: '4. Атмосферный',
      description: 'Подача нефти в П-3',
      reserves: ['Н-3А'],
    },
  },
  {
    id: 'P-1',
    type: 'furnace',
    label: 'П-1',
    x: 1160,
    y: 740,
    w: 100,
    h: 90,
    meta: {
      zone: '4. Атмосферный',
      description: 'Трубчатая печь (поток к К-2)',
    },
  },
  {
    id: 'P-2',
    type: 'furnace',
    label: 'П-2',
    x: 1280,
    y: 740,
    w: 100,
    h: 90,
    meta: {
      zone: '4. Атмосферный',
      description: 'Трубчатая печь (поток к К-2)',
    },
  },
  {
    id: 'P-3',
    type: 'furnace',
    label: 'П-3',
    x: 1400,
    y: 740,
    w: 100,
    h: 90,
    meta: {
      zone: '4. Атмосферный',
      description: 'Трубчатая печь (поток к К-2)',
    },
  },
  {
    id: 'X-1',
    type: 'heatExchanger',
    label: 'Х-1/3-5',
    x: 1080,
    y: 105,
    w: 90,
    h: 55,
    meta: {
      zone: '4. Атмосферный',
      description: 'Холодильники верха К-1',
    },
  },
  {
    id: 'AVZ-3',
    type: 'heatExchanger',
    label: 'АВЗ-3',
    x: 1080,
    y: 175,
    w: 70,
    h: 48,
    meta: {
      zone: '4. Атмосферный',
      description: 'Аппарат воздушного охлаждения у К-1 (вентилятор)',
    },
  },

  // ——— Блок ГДМ / К-12 (между атм. и стабилизацией по схеме) ———
  {
    id: 'K-12-2',
    type: 'column',
    label: 'К-12/2',
    x: 1540,
    y: 280,
    w: 64,
    h: 120,
    meta: {
      zone: '4–5. ГДМ',
      description: 'Отпарная колонна / реакторный блок К-12',
      trays: 4,
    },
  },
  {
    id: 'K-12-3',
    type: 'column',
    label: 'К-12/3',
    x: 1540,
    y: 420,
    w: 64,
    h: 120,
    meta: {
      zone: '4–5. ГДМ',
      description: 'Отпарная колонна К-12/3',
      trays: 4,
    },
  },
  {
    id: 'K-12-4',
    type: 'column',
    label: 'К-12/4',
    x: 1540,
    y: 560,
    w: 64,
    h: 100,
    meta: {
      zone: '4–5. ГДМ',
      description: 'Реактор К-12/4',
    },
  },
  {
    id: 'N-68',
    type: 'pump',
    label: 'Н-68',
    x: 1620,
    y: 620,
    w: 56,
    h: 56,
    meta: { zone: '4–5. ГДМ', description: 'Насос контура К-12' },
  },
  {
    id: 'N-23',
    type: 'pump',
    label: 'Н-23',
    x: 1620,
    y: 540,
    w: 56,
    h: 56,
    meta: { zone: '4–5. ГДМ', description: 'Насос Н-23' },
  },
  {
    id: 'N-49',
    type: 'pump',
    label: 'Н-49',
    x: 1620,
    y: 700,
    w: 56,
    h: 56,
    meta: { zone: '4–5. ГДМ', description: 'Насос Н-49' },
  },
  {
    id: 'N-110k',
    type: 'pump',
    label: 'Н-110к',
    x: 1620,
    y: 360,
    w: 56,
    h: 56,
    meta: { zone: '4–5. ГДМ', description: 'Насос Н-110к' },
  },
  {
    id: 'N-111k',
    type: 'pump',
    label: 'Н-111к',
    x: 1620,
    y: 440,
    w: 56,
    h: 56,
    meta: { zone: '4–5. ГДМ', description: 'Насос Н-111к' },
  },
  {
    id: 'X-15',
    type: 'heatExchanger',
    label: 'Х-15',
    x: 1700,
    y: 280,
    w: 64,
    h: 48,
    meta: { zone: '4–5. ГДМ', description: 'Холодильник Х-15' },
  },
  {
    id: 'X-19',
    type: 'heatExchanger',
    label: 'Х-19',
    x: 1700,
    y: 420,
    w: 64,
    h: 48,
    meta: { zone: '4–5. ГДМ', description: 'Холодильник Х-19' },
  },
  {
    id: 'X-24',
    type: 'heatExchanger',
    label: 'Х-24',
    x: 1700,
    y: 200,
    w: 64,
    h: 48,
    meta: { zone: '4–5. ГДМ', description: 'Холодильник Х-24' },
  },
  {
    id: 'X-8',
    type: 'heatExchanger',
    label: 'Х-8/1,2',
    x: 1700,
    y: 120,
    w: 80,
    h: 48,
    meta: { zone: '4–5. ГДМ', description: 'Холодильники Х-8/1,2' },
  },
  {
    id: 'S-1k',
    type: 'vessel',
    label: 'С-1к',
    x: 1700,
    y: 340,
    w: 64,
    h: 56,
    meta: { zone: '4–5. ГДМ', description: 'Сепаратор С-1к' },
  },
  {
    id: 'Sm-1k',
    type: 'group',
    label: 'См-1к',
    x: 1540,
    y: 200,
    w: 70,
    h: 48,
    meta: { zone: '4–5. ГДМ', description: 'Смеситель См-1к' },
  },
  {
    id: 'HV-15k',
    type: 'heatExchanger',
    label: 'ХВ-15к',
    x: 1700,
    y: 500,
    w: 70,
    h: 44,
    meta: { zone: '4–5. ГДМ', description: 'Воздухоохладитель ХВ-15к' },
  },
  {
    id: 'HV-30k',
    type: 'heatExchanger',
    label: 'ХВ-30к',
    x: 1780,
    y: 500,
    w: 70,
    h: 44,
    meta: { zone: '4–5. ГДМ', description: 'Воздухоохладитель ХВ-30к' },
  },
  {
    id: 'HV-31k',
    type: 'heatExchanger',
    label: 'ХВ-31к',
    x: 1860,
    y: 500,
    w: 70,
    h: 44,
    meta: { zone: '4–5. ГДМ', description: 'Воздухоохладитель ХВ-31к' },
  },
  {
    id: 'AVG-1',
    type: 'vessel',
    label: 'АВГ-1',
    x: 1780,
    y: 420,
    w: 70,
    h: 48,
    meta: { zone: '4–5. ГДМ', description: 'Аппарат воздушного охлаждения АВГ-1' },
  },

  // ——— Зона 5: К-2 + стриппинги ———
  {
    id: 'K-2',
    type: 'column',
    label: 'К-2',
    x: 1980,
    y: 180,
    w: 100,
    h: 400,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Вторая ректификационная колонна',
      trays: 43,
      designPressure: '3 кгс/см²',
      designTemp: '350 °C',
    },
  },
  {
    id: 'L-3',
    type: 'valve',
    label: 'Л-3',
    x: 2080,
    y: 580,
    w: 48,
    h: 48,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Вывод товарного мазута с низа К-2',
    },
  },
  {
    id: 'LRCA_604',
    type: 'signal',
    label: 'LRCA604',
    x: 1900,
    y: 360,
    w: 70,
    h: 36,
    meta: { zone: '5. К-2 / стриппинги', description: 'Уровень в К-2' },
  },
  {
    id: 'PRSA_213',
    type: 'signal',
    label: 'PRSA213',
    x: 1900,
    y: 300,
    w: 72,
    h: 36,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Давление верха К-2 (норма 0,2–1 кгс/см²)',
    },
  },
  {
    id: 'E-2-vessel',
    type: 'vessel',
    label: 'Е-2',
    x: 2120,
    y: 140,
    w: 70,
    h: 90,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Ёмкость-водоотделитель колонны К-2',
    },
  },
  {
    id: 'X-2',
    type: 'heatExchanger',
    label: 'Х-2/3-5',
    x: 2120,
    y: 80,
    w: 90,
    h: 48,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Холодильники верха / контура К-2',
    },
  },
  {
    id: 'AVZ-45',
    type: 'vessel',
    label: 'АВЗ-4,5',
    x: 2220,
    y: 80,
    w: 80,
    h: 48,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Аппараты воздушного охлаждения',
    },
  },
  {
    id: 'N-7',
    type: 'pump',
    label: 'Н-7',
    x: 2120,
    y: 260,
    w: 64,
    h: 64,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Орошение К-2 / откачка бензина в А-1',
      reserves: ['Н-7А'],
    },
  },
  {
    id: 'N-12',
    type: 'pump',
    label: 'Н-12',
    x: 2120,
    y: 360,
    w: 64,
    h: 64,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: '1-е циркуляционное орошение К-2',
      reserves: ['Н-12А'],
    },
  },
  {
    id: 'N-13',
    type: 'pump',
    label: 'Н-13',
    x: 2200,
    y: 360,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: '2 ц.о. К-2',
      reserves: ['Н-11'],
    },
  },
  {
    id: 'N-17',
    type: 'pump',
    label: 'Н-17',
    x: 2200,
    y: 440,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: '3 ц.о. К-2',
      reserves: ['Н-11', 'Н-19'],
    },
  },
  {
    id: 'N-6x',
    type: 'pump',
    label: 'Н-6х',
    x: 2200,
    y: 280,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Насос Н-6х (схема КТС)',
    },
  },
  {
    id: 'K-3-1',
    type: 'column',
    label: 'К-3/1',
    x: 2300,
    y: 200,
    w: 70,
    h: 160,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отпарная колонна, фр. 140–240 °C',
      trays: 10,
    },
  },
  {
    id: 'K-3-2',
    type: 'column',
    label: 'К-3/2',
    x: 2300,
    y: 390,
    w: 70,
    h: 160,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отпарная колонна, фр. 240–300 °C',
      trays: 10,
    },
  },
  {
    id: 'K-3-3',
    type: 'column',
    label: 'К-3/3',
    x: 2300,
    y: 580,
    w: 70,
    h: 160,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отпарная колонна, фр. 300–350 °C',
      trays: 10,
    },
  },
  {
    id: 'N-14',
    type: 'pump',
    label: 'Н-14',
    x: 2400,
    y: 250,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка фр. 140–240 °C из К-3/1',
      reserves: ['Н-67А', 'Н-35'],
    },
  },
  {
    id: 'N-15',
    type: 'pump',
    label: 'Н-15',
    x: 2400,
    y: 440,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка фр. 240–300 °C из К-3/2',
      reserves: ['Н-35'],
    },
  },
  {
    id: 'N-16',
    type: 'pump',
    label: 'Н-16',
    x: 2400,
    y: 630,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка фр. 300–350 °C',
      reserves: ['Н-16А'],
    },
  },
  {
    id: 'N-4',
    type: 'pump',
    label: 'Н-4',
    x: 2120,
    y: 640,
    w: 64,
    h: 64,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка мазута (потоки)',
      reserves: ['Н-4А'],
    },
  },
  {
    id: 'N-32',
    type: 'pump',
    label: 'Н-32',
    x: 2120,
    y: 740,
    w: 64,
    h: 64,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка 2 потока мазута',
      reserves: ['Н-32А'],
    },
  },
  {
    id: 'A-1',
    type: 'vessel',
    label: 'А-1',
    x: 1980,
    y: 640,
    w: 80,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отстойник защелачивания бензина',
    },
  },
  {
    id: 'A-2-1',
    type: 'vessel',
    label: 'А-2/1',
    x: 1980,
    y: 720,
    w: 80,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отстойник бензина от щелочи',
    },
  },
  {
    id: 'T-20',
    type: 'heatExchanger',
    label: 'Т-20',
    x: 2220,
    y: 520,
    w: 64,
    h: 48,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Теплообменник 3 ц.о. К-2',
    },
  },

  // ——— Зона 6: Стабилизация / газ ———
  {
    id: 'K-4',
    type: 'column',
    label: 'К-4',
    x: 2580,
    y: 220,
    w: 80,
    h: 280,
    meta: {
      zone: '6. Стабилизация',
      description: 'Стабилизационная колонна бензина',
      trays: 34,
      designPressure: '13 кгс/см²',
      designTemp: '180 °C',
    },
  },
  {
    id: 'E-3-vessel',
    type: 'vessel',
    label: 'Е-3',
    x: 2690,
    y: 200,
    w: 70,
    h: 80,
    meta: {
      zone: '6. Стабилизация',
      description: 'Рефлюксная ёмкость орошения К-4',
    },
  },
  {
    id: 'E-1K',
    type: 'vessel',
    label: 'Е-1К',
    x: 2690,
    y: 100,
    w: 70,
    h: 70,
    meta: {
      zone: '6. Стабилизация',
      description: 'Ёмкость-испаритель бутановой фракции',
    },
  },
  {
    id: 'T-1K',
    type: 'heatExchanger',
    label: 'Т-1К',
    x: 2500,
    y: 85,
    w: 70,
    h: 48,
    meta: {
      zone: '6. Стабилизация',
      description: 'Теплообменник Т-1К',
    },
  },
  {
    id: 'N-10',
    type: 'pump',
    label: 'Н-10',
    x: 2690,
    y: 310,
    w: 64,
    h: 64,
    meta: {
      zone: '6. Стабилизация',
      description: 'Орошение К-4 / откачка ПБФ',
      reserves: ['Н-10А'],
    },
  },
  {
    id: 'K-7',
    type: 'column',
    label: 'К-7',
    x: 2580,
    y: 560,
    w: 80,
    h: 220,
    meta: {
      zone: '6. Стабилизация',
      description: 'Газосепаратор (колонна К-7)',
      trays: 37,
      designPressure: '6 кгс/см²',
    },
  },
  {
    id: 'N-47',
    type: 'pump',
    label: 'Н-47',
    x: 2690,
    y: 620,
    w: 64,
    h: 64,
    meta: {
      zone: '6. Стабилизация',
      description: 'Подача фр. 140–240 °C в К-7',
      reserves: ['Н-48'],
    },
  },
  {
    id: 'N-78',
    type: 'pump',
    label: 'Н-78',
    x: 2690,
    y: 720,
    w: 56,
    h: 56,
    meta: {
      zone: '6. Стабилизация',
      description: 'Насос Н-78 (схема КТС)',
      reserves: ['Н-78А'],
    },
  },
  {
    id: 'X-4',
    type: 'heatExchanger',
    label: 'Х-4/1-3',
    x: 2500,
    y: 145,
    w: 90,
    h: 55,
    meta: {
      zone: '6. Стабилизация',
      description: 'Холодильники контура К-4',
    },
  },
  {
    id: 'T-14',
    type: 'heatExchanger',
    label: 'Т-14',
    x: 2500,
    y: 420,
    w: 70,
    h: 55,
    meta: { zone: '6. Стабилизация', description: 'Теплообменник контура стабилизации' },
  },
  {
    id: 'T-15-1',
    type: 'heatExchanger',
    label: 'Т-15/1',
    x: 2500,
    y: 500,
    w: 70,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Теплообменник Т-15/1' },
  },
  {
    id: 'T-15-2',
    type: 'heatExchanger',
    label: 'Т-15/2',
    x: 2500,
    y: 800,
    w: 70,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Теплообменник Т-15/2' },
  },
  {
    id: 'T-16',
    type: 'heatExchanger',
    label: 'Т-16',
    x: 2780,
    y: 420,
    w: 70,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Теплообменник Т-16' },
  },
  {
    id: 'X-5',
    type: 'heatExchanger',
    label: 'Х-5,6',
    x: 2780,
    y: 500,
    w: 70,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Холодильники Х-5,6' },
  },
  {
    id: 'X-7',
    type: 'heatExchanger',
    label: 'Х-7',
    x: 2780,
    y: 560,
    w: 64,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Холодильник Х-7' },
  },
  {
    id: 'X-9',
    type: 'heatExchanger',
    label: 'Х-9',
    x: 2780,
    y: 360,
    w: 64,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Холодильник Х-9' },
  },
  {
    id: 'X-12',
    type: 'heatExchanger',
    label: 'Х-12',
    x: 2780,
    y: 300,
    w: 64,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Холодильник Х-12' },
  },
  {
    id: 'T-30',
    type: 'heatExchanger',
    label: 'Т-30',
    x: 2780,
    y: 140,
    w: 70,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Теплообменник Т-30' },
  },
  {
    id: 'X-11',
    type: 'heatExchanger',
    label: 'Х-11',
    x: 2500,
    y: 900,
    w: 70,
    h: 48,
    meta: { zone: '6. Стабилизация', description: 'Холодильник Х-11' },
  },
  {
    id: 'A-2-2',
    type: 'vessel',
    label: 'А-2/2',
    x: 2580,
    y: 900,
    w: 70,
    h: 56,
    meta: {
      zone: '6. Стабилизация',
      description: 'Отстойник керосина от воды',
    },
  },
  {
    id: 'A-3',
    type: 'vessel',
    label: 'А-3',
    x: 2660,
    y: 900,
    w: 64,
    h: 56,
    meta: {
      zone: '6. Стабилизация',
      description: 'Отстойник керосина от воды',
    },
  },
  {
    id: 'A-4',
    type: 'vessel',
    label: 'А-4',
    x: 2740,
    y: 900,
    w: 64,
    h: 56,
    meta: {
      zone: '6. Стабилизация',
      description: 'Отстойник керосина от воды',
    },
  },
  {
    id: 'A-5',
    type: 'vessel',
    label: 'А-5',
    x: 2820,
    y: 900,
    w: 64,
    h: 56,
    meta: {
      zone: '6. Стабилизация',
      description: 'Отстойник керосина от воды',
    },
  },

  // ——— Зона 7: Вторичная перегонка бензина ———
  {
    id: 'N-57',
    type: 'pump',
    label: 'Н-57',
    x: 2920,
    y: 520,
    w: 64,
    h: 64,
    meta: {
      zone: '7. Вторичная',
      description: 'Подача сырья в К-9 из парков',
      reserves: ['Н-57А'],
    },
  },
  {
    id: 'K-9',
    type: 'column',
    label: 'К-9',
    x: 3020,
    y: 180,
    w: 90,
    h: 360,
    meta: {
      zone: '7. Вторичная',
      description: 'Ректификационная колонна вторичной перегонки',
      trays: 60,
      designPressure: '4,5 кгс/см²',
      designTemp: '170 °C',
    },
  },
  {
    id: 'K-10',
    type: 'column',
    label: 'К-10',
    x: 3220,
    y: 180,
    w: 90,
    h: 360,
    meta: {
      zone: '7. Вторичная',
      description: 'Ректификационная колонна вторичной перегонки',
      trays: 60,
      designPressure: '2,0 кгс/см²',
      designTemp: '200 °C',
    },
  },
  {
    id: 'E-18',
    type: 'vessel',
    label: 'Е-18',
    x: 3140,
    y: 100,
    w: 70,
    h: 70,
    meta: {
      zone: '7. Вторичная',
      description: 'Рефлюксная ёмкость колонны К-9',
    },
  },
  {
    id: 'E-17',
    type: 'vessel',
    label: 'Е-17',
    x: 3320,
    y: 100,
    w: 70,
    h: 70,
    meta: {
      zone: '7. Вторичная',
      description: 'Рефлюксная ёмкость колонны К-10',
    },
  },
  {
    id: 'N-54',
    type: 'pump',
    label: 'Н-54',
    x: 3140,
    y: 355,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Орошение К-9 / откачка НК-62 °C',
      reserves: ['Н-54А'],
    },
  },
  {
    id: 'N-55',
    type: 'pump',
    label: 'Н-55',
    x: 3320,
    y: 320,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Орошение К-10 / фр. 62–105 °C',
      reserves: ['Н-56', 'Н-59'],
    },
  },
  {
    id: 'P-4',
    type: 'furnace',
    label: 'П-4',
    x: 3100,
    y: 620,
    w: 120,
    h: 90,
    meta: {
      zone: '7. Вторичная',
      description:
        'Печь рибойлинга К-9 / К-10. Вне атмосферного тракта сценария — управление топливом здесь не моделируется.',
    },
  },
  {
    id: 'N-76',
    type: 'pump',
    label: 'Н-76',
    x: 3020,
    y: 740,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Циркуляция низа К-9 через П-4',
      reserves: ['Н-79'],
    },
  },
  {
    id: 'N-77',
    type: 'pump',
    label: 'Н-77',
    x: 3240,
    y: 740,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Циркуляция низа К-10 через П-4',
      reserves: ['Н-77А'],
    },
  },
  {
    id: 'N-58',
    type: 'pump',
    label: 'Н-58',
    x: 3320,
    y: 560,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Откачка фракции низа К-10 с установки',
      reserves: ['Н-58А'],
    },
  },
  {
    id: 'AVZ-12',
    type: 'vessel',
    label: 'АВЗ-1,2',
    x: 3140,
    y: 220,
    w: 80,
    h: 48,
    meta: {
      zone: '7. Вторичная',
      description: 'Аппараты воздушного охлаждения',
    },
  },
  {
    id: 'X-20',
    type: 'heatExchanger',
    label: 'Х-20,21',
    x: 3140,
    y: 280,
    w: 80,
    h: 48,
    meta: {
      zone: '7. Вторичная',
      description: 'Холодильники Х-20,21/1,2',
    },
  },
  {
    id: 'X-22',
    type: 'heatExchanger',
    label: 'Х-22,21/2',
    x: 3320,
    y: 220,
    w: 80,
    h: 48,
    meta: {
      zone: '7. Вторичная',
      description: 'Холодильники Х-22,21/2',
    },
  },
  {
    id: 'X-26',
    type: 'heatExchanger',
    label: 'Х-26/2,3',
    x: 2920,
    y: 280,
    w: 80,
    h: 48,
    meta: {
      zone: '7. Вторичная',
      description: 'Холодильники Х-26/2,3',
    },
  },
  {
    id: 'X-27',
    type: 'heatExchanger',
    label: 'Х-27',
    x: 3320,
    y: 400,
    w: 64,
    h: 48,
    meta: {
      zone: '7. Вторичная',
      description: 'Холодильник Х-27',
    },
  },
  {
    id: 'X-25K',
    type: 'heatExchanger',
    label: 'Х-25К',
    x: 3320,
    y: 460,
    w: 70,
    h: 48,
    meta: {
      zone: '7. Вторичная',
      description: 'Холодильники Х-25К,23/2,1',
    },
  },
  {
    id: 'T-25-1',
    type: 'heatExchanger',
    label: 'Т-25/1',
    x: 2920,
    y: 360,
    w: 70,
    h: 48,
    meta: {
      zone: '7. Вторичная',
      description: 'Теплообменник Т-25/1',
    },
  },

  // Zone banners
  {
    id: 'zone-1',
    type: 'label',
    label: '1. Сырьё',
    x: 40,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '1. Сырьё' },
  },
  {
    id: 'UTIL-block',
    type: 'group',
    label: 'Утилиты\nпар · вода · воздух · вент.',
    x: 40,
    y: 80,
    w: 200,
    h: 70,
    meta: {
      zone: '1. Сырьё',
      description:
        'Учебный блок утилит: пар, оборотная вода, приборный воздух, вентиляция (SC-02…06, 09–10).',
    },
  },
  {
    id: 'zone-2',
    type: 'label',
    label: '2. Подогрев',
    x: 340,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '2. Подогрев' },
  },
  {
    id: 'zone-3',
    type: 'label',
    label: '3. ЭЛОУ',
    x: 660,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '3. ЭЛОУ' },
  },
  {
    id: 'zone-4',
    type: 'label',
    label: '4. Атмосферный',
    x: 1160,
    y: 40,
    w: 180,
    h: 32,
    meta: { zone: '4. Атмосферный' },
  },
  {
    id: 'zone-gdm',
    type: 'label',
    label: 'ГДМ / К-12',
    x: 1540,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '4–5. ГДМ' },
  },
  {
    id: 'zone-5',
    type: 'label',
    label: '5. К-2 / стриппинги',
    x: 1980,
    y: 40,
    w: 200,
    h: 32,
    meta: { zone: '5. К-2 / стриппинги' },
  },
  {
    id: 'zone-6',
    type: 'label',
    label: '6. Стабилизация',
    x: 2500,
    y: 40,
    w: 180,
    h: 32,
    meta: { zone: '6. Стабилизация' },
  },
  {
    id: 'zone-7',
    type: 'label',
    label: '7. Вторичная',
    x: 3020,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '7. Вторичная' },
  },
]

export const equipmentById = Object.fromEntries(
  equipment.map((e) => [e.id, e]),
) as Record<string, EquipmentNode>
