import type { EquipmentNode } from './types'

/**
 * Каталог оборудования мнемосхемы ЭЛОУ-АВТ (полная топология по схеме КТС / регламенту).
 * Координаты — SCADA-раскладка по зонам процесса (слева направо), не пиксели PDF.
 */
export const equipment: EquipmentNode[] = [
  // ——— Зона 1: Сырьё / парки ———
  {
    id: 'parks-55-5',
    type: 'group',
    label: 'Парки тит. 55/5',
    x: 40,
    y: 480,
    w: 140,
    h: 160,
    meta: {
      zone: '1. Сырьё',
      description: 'Резервуары Р-10…Р-15: сырая нефть, бензины, некондиция',
    },
  },
  {
    id: 'feed-crude',
    type: 'label',
    label: 'Сырая нефть',
    x: 60,
    y: 400,
    w: 100,
    h: 36,
    meta: { zone: '1. Сырьё', description: 'Подача с КС / парков на приём Н-1' },
  },
  {
    id: 'N-1',
    type: 'pump',
    label: 'Н-1',
    x: 200,
    y: 520,
    w: 72,
    h: 72,
    meta: {
      zone: '1. Сырьё',
      description: 'Сырьевой насос',
      reserves: ['Н-1А', 'Н-1Б', 'Н-1В'],
      designPressure: '19,5 кгс/см²',
    },
  },

  // ——— Зона 2: Подогрев сырой нефти ———
  {
    id: 'HX-stream-1',
    type: 'heatExchanger',
    label: 'Т-1…Т-3\n(1 поток)',
    x: 340,
    y: 280,
    w: 110,
    h: 70,
    meta: {
      zone: '2. Подогрев',
      description: '1 поток: Т-1/1-3, Т-2, Т-3/1-2 — нагрев до ЭЛОУ',
    },
  },
  {
    id: 'HX-stream-2',
    type: 'heatExchanger',
    label: 'Т-4…Т-7\n(2 поток)',
    x: 340,
    y: 420,
    w: 110,
    h: 70,
    meta: {
      zone: '2. Подогрев',
      description: '2 поток: Т-4/1-2, Т-5, Т-6/1-2, Т-7/1',
    },
  },
  {
    id: 'HX-stream-3',
    type: 'heatExchanger',
    label: 'Т-7…Т-11\n(3 поток)',
    x: 340,
    y: 560,
    w: 110,
    h: 70,
    meta: {
      zone: '2. Подогрев',
      description: '3 поток: Т-7/2, Т-8, Т-9…Т-11; t ≤ 140 °C',
    },
  },
  {
    id: 'HX-block-label',
    type: 'group',
    label: 'Бл. подогрева\nсырой нефти',
    x: 470,
    y: 380,
    w: 120,
    h: 90,
    meta: {
      zone: '2. Подогрев',
      description: 'Три параллельных потока Т-1…Т-11 перед ЭЛОУ',
    },
  },

  // ——— Зона 3: ЭЛОУ ———
  {
    id: 'E-1',
    type: 'desalter',
    label: 'Э-1',
    x: 660,
    y: 260,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 1 ступени' },
  },
  {
    id: 'E-3',
    type: 'desalter',
    label: 'Э-3',
    x: 750,
    y: 260,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 1 ступени' },
  },
  {
    id: 'E-5',
    type: 'desalter',
    label: 'Э-5',
    x: 840,
    y: 260,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 1 ступени' },
  },
  {
    id: 'E-2',
    type: 'desalter',
    label: 'Э-2',
    x: 660,
    y: 340,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 2 ступени' },
  },
  {
    id: 'E-4',
    type: 'desalter',
    label: 'Э-4',
    x: 750,
    y: 340,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 2 ступени' },
  },
  {
    id: 'E-6',
    type: 'desalter',
    label: 'Э-6',
    x: 840,
    y: 340,
    w: 70,
    h: 50,
    meta: { zone: '3. ЭЛОУ', description: 'Электродегидратор 2 ступени' },
  },
  {
    id: 'ELOU-block',
    type: 'group',
    label: 'ЭЛОУ',
    x: 640,
    y: 220,
    w: 290,
    h: 200,
    meta: {
      zone: '3. ЭЛОУ',
      description: 'Блок обессоливания: Э-1…Э-6, две ступени; вода + деэмульгатор',
    },
  },
  {
    id: 'E-15',
    type: 'vessel',
    label: 'Е-15',
    x: 960,
    y: 300,
    w: 80,
    h: 100,
    meta: {
      zone: '3. ЭЛОУ',
      description: 'Буферная ёмкость обессоленной нефти после ЭЛОУ',
      designPressure: '5,3 кгс/см²',
      designTemp: '110 °C',
    },
  },
  {
    id: 'E-16',
    type: 'vessel',
    label: 'Е-16',
    x: 960,
    y: 440,
    w: 80,
    h: 70,
    meta: {
      zone: '3. ЭЛОУ',
      description: 'Отстойник соляного раствора',
    },
  },

  // ——— Зона 4: Атмосферный блок К-1 / печи ———
  {
    id: 'HX-desalted',
    type: 'heatExchanger',
    label: 'Бл. подогрева\nобесс. нефти',
    x: 1080,
    y: 280,
    w: 120,
    h: 80,
    meta: {
      zone: '4. Атмосферный',
      description: 'Подогрев обессоленной нефти перед К-1 / печами',
    },
  },
  {
    id: 'K-1',
    type: 'column',
    label: 'К-1',
    x: 1260,
    y: 200,
    w: 90,
    h: 320,
    meta: {
      zone: '4. Атмосферный',
      description: 'Первая ректификационная колонна',
      trays: 28,
      designPressure: '6 кгс/см²',
      designTemp: '300 °C',
    },
  },
  {
    id: 'E-1-vessel',
    type: 'vessel',
    label: 'Е-1',
    x: 1380,
    y: 180,
    w: 70,
    h: 90,
    meta: {
      zone: '4. Атмосферный',
      description: 'Ёмкость-водоотделитель колонны К-1',
    },
  },
  {
    id: 'N-6',
    type: 'pump',
    label: 'Н-6',
    x: 1380,
    y: 300,
    w: 64,
    h: 64,
    meta: {
      zone: '4. Атмосферный',
      description: 'Орошение К-1 / сырьё в К-4',
      reserves: ['Н-6А'],
    },
  },
  {
    id: 'N-2',
    type: 'pump',
    label: 'Н-2',
    x: 1180,
    y: 580,
    w: 64,
    h: 64,
    meta: {
      zone: '4. Атмосферный',
      description: 'Подача нефти в П-1, П-2',
      reserves: ['Н-2А', 'Н-2Б'],
    },
  },
  {
    id: 'N-3',
    type: 'pump',
    label: 'Н-3',
    x: 1280,
    y: 580,
    w: 64,
    h: 64,
    meta: {
      zone: '4. Атмосферный',
      description: 'Подача нефти в П-3',
      reserves: ['Н-3А'],
    },
  },
  {
    id: 'P-1',
    type: 'furnace',
    label: 'П-1',
    x: 1160,
    y: 700,
    w: 100,
    h: 90,
    meta: {
      zone: '4. Атмосферный',
      description: 'Трубчатая печь (поток к К-2)',
    },
  },
  {
    id: 'P-2',
    type: 'furnace',
    label: 'П-2',
    x: 1280,
    y: 700,
    w: 100,
    h: 90,
    meta: {
      zone: '4. Атмосферный',
      description: 'Трубчатая печь (поток к К-2)',
    },
  },
  {
    id: 'P-3',
    type: 'furnace',
    label: 'П-3',
    x: 1400,
    y: 700,
    w: 100,
    h: 90,
    meta: {
      zone: '4. Атмосферный',
      description: 'Трубчатая печь (поток к К-2)',
    },
  },
  {
    id: 'X-1',
    type: 'heatExchanger',
    label: 'Х-1/3-5',
    x: 1380,
    y: 100,
    w: 90,
    h: 55,
    meta: {
      zone: '4. Атмосферный',
      description: 'Холодильники верха К-1',
    },
  },

  // ——— Зона 5: К-2 + стриппинги ———
  {
    id: 'K-2',
    type: 'column',
    label: 'К-2',
    x: 1620,
    y: 160,
    w: 100,
    h: 400,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Вторая ректификационная колонна',
      trays: 43,
      designPressure: '3 кгс/см²',
      designTemp: '350 °C',
    },
  },
  {
    id: 'E-2-vessel',
    type: 'vessel',
    label: 'Е-2',
    x: 1760,
    y: 140,
    w: 70,
    h: 90,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Ёмкость-водоотделитель колонны К-2',
    },
  },
  {
    id: 'N-7',
    type: 'pump',
    label: 'Н-7',
    x: 1760,
    y: 260,
    w: 64,
    h: 64,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Орошение К-2 / откачка бензина в А-1',
      reserves: ['Н-7А'],
    },
  },
  {
    id: 'N-12',
    type: 'pump',
    label: 'Н-12',
    x: 1760,
    y: 360,
    w: 64,
    h: 64,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: '1-е циркуляционное орошение К-2',
      reserves: ['Н-12А'],
    },
  },
  {
    id: 'K-3-1',
    type: 'column',
    label: 'К-3/1',
    x: 1880,
    y: 200,
    w: 70,
    h: 160,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отпарная колонна, фр. 140–240 °C',
      trays: 10,
    },
  },
  {
    id: 'K-3-2',
    type: 'column',
    label: 'К-3/2',
    x: 1880,
    y: 390,
    w: 70,
    h: 160,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отпарная колонна, фр. 240–300 °C',
      trays: 10,
    },
  },
  {
    id: 'K-3-3',
    type: 'column',
    label: 'К-3/3',
    x: 1880,
    y: 580,
    w: 70,
    h: 160,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отпарная колонна, фр. 300–350 °C',
      trays: 10,
    },
  },
  {
    id: 'N-14',
    type: 'pump',
    label: 'Н-14',
    x: 1980,
    y: 250,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка фр. 140–240 °C из К-3/1',
      reserves: ['Н-67А', 'Н-35'],
    },
  },
  {
    id: 'N-15',
    type: 'pump',
    label: 'Н-15',
    x: 1980,
    y: 440,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка фр. 240–300 °C из К-3/2',
      reserves: ['Н-35'],
    },
  },
  {
    id: 'N-16',
    type: 'pump',
    label: 'Н-16',
    x: 1980,
    y: 630,
    w: 56,
    h: 56,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка фр. 300–350 °C',
      reserves: ['Н-16А'],
    },
  },
  {
    id: 'N-4',
    type: 'pump',
    label: 'Н-4',
    x: 1760,
    y: 620,
    w: 64,
    h: 64,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка мазута (потоки)',
      reserves: ['Н-4А'],
    },
  },
  {
    id: 'N-32',
    type: 'pump',
    label: 'Н-32',
    x: 1760,
    y: 720,
    w: 64,
    h: 64,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Откачка 2 потока мазута',
      reserves: ['Н-32А'],
    },
  },
  {
    id: 'A-1',
    type: 'vessel',
    label: 'А-1, А-2/1',
    x: 1620,
    y: 620,
    w: 100,
    h: 60,
    meta: {
      zone: '5. К-2 / стриппинги',
      description: 'Отстойники защелачивания бензина',
    },
  },

  // ——— Зона 6: Стабилизация / газ ———
  {
    id: 'K-4',
    type: 'column',
    label: 'К-4',
    x: 2180,
    y: 220,
    w: 80,
    h: 280,
    meta: {
      zone: '6. Стабилизация',
      description: 'Стабилизационная колонна бензина',
      trays: 34,
      designPressure: '13 кгс/см²',
      designTemp: '180 °C',
    },
  },
  {
    id: 'E-3-vessel',
    type: 'vessel',
    label: 'Е-3',
    x: 2290,
    y: 200,
    w: 70,
    h: 80,
    meta: {
      zone: '6. Стабилизация',
      description: 'Рефлюксная ёмкость орошения К-4',
    },
  },
  {
    id: 'N-10',
    type: 'pump',
    label: 'Н-10',
    x: 2290,
    y: 310,
    w: 64,
    h: 64,
    meta: {
      zone: '6. Стабилизация',
      description: 'Орошение К-4 / откачка ПБФ',
      reserves: ['Н-10А'],
    },
  },
  {
    id: 'K-7',
    type: 'column',
    label: 'К-7',
    x: 2180,
    y: 560,
    w: 80,
    h: 220,
    meta: {
      zone: '6. Стабилизация',
      description: 'Газосепаратор (колонна К-7)',
      trays: 37,
      designPressure: '6 кгс/см²',
    },
  },
  {
    id: 'N-47',
    type: 'pump',
    label: 'Н-47',
    x: 2290,
    y: 620,
    w: 64,
    h: 64,
    meta: {
      zone: '6. Стабилизация',
      description: 'Подача фр. 140–240 °C в К-7',
      reserves: ['Н-48'],
    },
  },
  {
    id: 'X-4',
    type: 'heatExchanger',
    label: 'Х-4/1-3',
    x: 2100,
    y: 140,
    w: 90,
    h: 55,
    meta: {
      zone: '6. Стабилизация',
      description: 'Холодильники контура К-4',
    },
  },
  {
    id: 'T-14',
    type: 'heatExchanger',
    label: 'Т-14',
    x: 2100,
    y: 420,
    w: 70,
    h: 55,
    meta: { zone: '6. Стабилизация', description: 'Теплообменник контура стабилизации' },
  },
  {
    id: 'P-3-stab',
    type: 'furnace',
    label: 'П-3*',
    x: 2180,
    y: 820,
    w: 90,
    h: 80,
    meta: {
      zone: '6. Стабилизация',
      description: 'Контур нагрева (связь с атмосферным блоком)',
    },
  },

  // ——— Зона 7: Вторичная перегонка бензина ———
  {
    id: 'N-57',
    type: 'pump',
    label: 'Н-57',
    x: 2460,
    y: 520,
    w: 64,
    h: 64,
    meta: {
      zone: '7. Вторичная',
      description: 'Подача сырья в К-9 из парков',
      reserves: ['Н-57А'],
    },
  },
  {
    id: 'K-9',
    type: 'column',
    label: 'К-9',
    x: 2580,
    y: 180,
    w: 90,
    h: 360,
    meta: {
      zone: '7. Вторичная',
      description: 'Ректификационная колонна вторичной перегонки',
      trays: 60,
      designPressure: '4,5 кгс/см²',
      designTemp: '170 °C',
    },
  },
  {
    id: 'K-10',
    type: 'column',
    label: 'К-10',
    x: 2780,
    y: 180,
    w: 90,
    h: 360,
    meta: {
      zone: '7. Вторичная',
      description: 'Ректификационная колонна вторичной перегонки',
      trays: 60,
      designPressure: '2,0 кгс/см²',
      designTemp: '200 °C',
    },
  },
  {
    id: 'E-18',
    type: 'vessel',
    label: 'Е-18',
    x: 2700,
    y: 120,
    w: 70,
    h: 70,
    meta: {
      zone: '7. Вторичная',
      description: 'Рефлюксная ёмкость колонны К-9',
    },
  },
  {
    id: 'E-17',
    type: 'vessel',
    label: 'Е-17',
    x: 2900,
    y: 120,
    w: 70,
    h: 70,
    meta: {
      zone: '7. Вторичная',
      description: 'Рефлюксная ёмкость колонны К-10',
    },
  },
  {
    id: 'N-54',
    type: 'pump',
    label: 'Н-54',
    x: 2700,
    y: 320,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Орошение К-9 / откачка НК-62 °C',
      reserves: ['Н-54А'],
    },
  },
  {
    id: 'N-55',
    type: 'pump',
    label: 'Н-55',
    x: 2900,
    y: 320,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Орошение К-10 / фр. 62–105 °C',
      reserves: ['Н-56', 'Н-59'],
    },
  },
  {
    id: 'P-4',
    type: 'furnace',
    label: 'П-4',
    x: 2660,
    y: 620,
    w: 120,
    h: 90,
    meta: {
      zone: '7. Вторичная',
      description: 'Печь рибойлинга К-9 / К-10',
    },
  },
  {
    id: 'N-76',
    type: 'pump',
    label: 'Н-76',
    x: 2580,
    y: 740,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Циркуляция низа К-9 через П-4',
      reserves: ['Н-79'],
    },
  },
  {
    id: 'N-77',
    type: 'pump',
    label: 'Н-77',
    x: 2800,
    y: 740,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Циркуляция низа К-10 через П-4',
      reserves: ['Н-77А'],
    },
  },
  {
    id: 'N-58',
    type: 'pump',
    label: 'Н-58',
    x: 2900,
    y: 560,
    w: 56,
    h: 56,
    meta: {
      zone: '7. Вторичная',
      description: 'Откачка фракции низа К-10 с установки',
      reserves: ['Н-58А'],
    },
  },
  {
    id: 'X-20',
    type: 'heatExchanger',
    label: 'Х-20…27',
    x: 3000,
    y: 280,
    w: 90,
    h: 60,
    meta: {
      zone: '7. Вторичная',
      description: 'Блок холодильников вторичной перегонки',
    },
  },

  // Zone banners (non-interactive visual markers — still selectable for info)
  {
    id: 'zone-1',
    type: 'label',
    label: '1. Сырьё',
    x: 40,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '1. Сырьё' },
  },
  {
    id: 'zone-2',
    type: 'label',
    label: '2. Подогрев',
    x: 340,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '2. Подогрев' },
  },
  {
    id: 'zone-3',
    type: 'label',
    label: '3. ЭЛОУ',
    x: 660,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '3. ЭЛОУ' },
  },
  {
    id: 'zone-4',
    type: 'label',
    label: '4. Атмосферный',
    x: 1160,
    y: 40,
    w: 180,
    h: 32,
    meta: { zone: '4. Атмосферный' },
  },
  {
    id: 'zone-5',
    type: 'label',
    label: '5. К-2 / стриппинги',
    x: 1620,
    y: 40,
    w: 200,
    h: 32,
    meta: { zone: '5. К-2 / стриппинги' },
  },
  {
    id: 'zone-6',
    type: 'label',
    label: '6. Стабилизация',
    x: 2100,
    y: 40,
    w: 180,
    h: 32,
    meta: { zone: '6. Стабилизация' },
  },
  {
    id: 'zone-7',
    type: 'label',
    label: '7. Вторичная',
    x: 2580,
    y: 40,
    w: 160,
    h: 32,
    meta: { zone: '7. Вторичная' },
  },
]

export const equipmentById = Object.fromEntries(
  equipment.map((e) => [e.id, e]),
) as Record<string, EquipmentNode>
